package util.neuralnet;

public enum DataContent {
	TCONTRASTR, TCONTRASTG, TCONTRASTB, AVGCONTRAST, LUMCONTRAST, DIRECTIONALITY, COARSENESS, RNESS, RLOW, RMID, RHIGH, GNESS, GLOW, GMID, GHIGH, BNESS, BLOW, BMID, BHIGH
}
